[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y tesseract-ocr tesseract-ocr-eng",
    "apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 libgl1-mesa-dri",
    "apt-get install -y python3-pip python3-venv"
]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python3 main.py"