[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y tesseract-ocr tesseract-ocr-eng",
    "apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 libgl1-mesa-dri libgl1",
    "apt-get install -y python3-pip python3-venv"
]

[phases.install]
cmds = ["/usr/bin/python3 -m pip install -r requirements.txt --break-system-packages"]

[phases.build]
cmds = [
    "echo 'Build completed'",
    "echo 'Pre-downloading PaddleOCR models...'",
    "/usr/bin/python3 -c \"import os; os.environ['HOME'] = '/root'; from paddleocr import PaddleOCR; ocr = PaddleOCR(use_angle_cls=True, lang='en', show_log=False); print('Models downloaded successfully')\"",
    "echo 'PaddleOCR models pre-downloaded to /root/.paddleocr/'"
]

[start]
cmd = "cd /app && /usr/bin/python3 main.py"