[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y tesseract-ocr tesseract-ocr-eng",
    "apt-get install -y libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python main.py"