name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: ["eng", "deu", "eng+deu"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Smoke test pipeline
        run: |
          python pipeline.py ActualBill.png --lang ${{ matrix.lang }} > /tmp/out.json
      - name: Run tests
        run: pytest -q
